spring:
  datasource:
    url: jdbc:postgresql://localhost:1111/wallet_db
    password: 123
    username: test_user
    driver-class-name: org.postgresql.Driver

datasource:
  table:
    name: wallet
    logName: wallet_operation

liquibase:
  test_data: true